import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Schema matching SeaORM entities exactly
export default defineSchema({
  // ==========================================================================
  // groups - WhatsApp groups for monitoring (matches entity/group.rs)
  // ==========================================================================
  groups: defineTable({
    jid: v.string(), // Primary key
    name: v.string(),
    description: v.optional(v.string()),
    monitored: v.boolean(), // NOT isMonitored
    addedAt: v.number(), // DateTimeUtc as timestamp
    lastMessage: v.optional(v.number()),
    messageCount: v.number(),
  })
    .index("by_jid", ["jid"])
    .index("by_name", ["name"])
    .index("by_monitored", ["monitored"]),

  // ==========================================================================
  // rawMessages - Incoming WhatsApp messages (matches entity/raw_message.rs)
  // ==========================================================================
  rawMessages: defineTable({
    // id is auto-generated by Convex, but we use externalId for the SeaORM id
    externalId: v.optional(v.string()), // maps to id in SeaORM
    groupJid: v.string(),
    groupName: v.string(),
    senderJid: v.string(),
    senderPhone: v.optional(v.string()),
    senderName: v.optional(v.string()),
    content: v.string(),
    timestamp: v.number(), // DateTimeUtc
    processedAt: v.optional(v.number()),
    error: v.optional(v.string()),
    replyToId: v.optional(v.string()),
    replyToContent: v.optional(v.string()),
    replyToSender: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_external_id", ["externalId"])
    .index("by_group", ["groupJid"])
    .index("by_timestamp", ["timestamp"])
    .index("by_processed", ["processedAt"]),

  // ==========================================================================
  // offers - Medication supply offers (matches entity/offer.rs)
  // ==========================================================================
  offers: defineTable({
    // id generated by Convex, SeaORM uses String UUID
    rawMessageId: v.string(), // NOT v.id, matches SeaORM String FK
    sourcePhone: v.string(),
    sourceName: v.optional(v.string()),
    sourceGroup: v.string(),
    medication: v.string(),
    medicationRaw: v.string(),
    quantity: v.optional(v.number()), // Decimal(10,2) as number
    unit: v.optional(v.string()),
    price: v.optional(v.number()), // Decimal(10,2) as number
    currency: v.optional(v.string()),
    expiryDate: v.optional(v.string()), // Date as ISO string
    batchNumber: v.optional(v.string()),
    notes: v.optional(v.string()),
    status: v.string(), // ItemStatus: "ACTIVE" | "MATCHED" | "EXPIRED" | "CANCELLED" | "DUPLICATE"
    urgencyLevel: v.string(), // UrgencyLevel: "NORMAL" | "SOON" | "URGENT" | "CRITICAL"
    expiryInfo: v.optional(v.string()),
    aiConfidence: v.number(), // f64
    contentEmbedding: v.optional(v.array(v.number())), // PgVector(768)
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_medication", ["medication"])
    .index("by_source", ["sourcePhone"])
    .index("by_raw_message", ["rawMessageId"])
    .index("by_created", ["createdAt"])
    .vectorIndex("by_embedding", {
      vectorField: "contentEmbedding",
      dimensions: 768,
      filterFields: ["status"],
    })
    .searchIndex("search_medication", {
      searchField: "medication",
      filterFields: ["status"],
    }),

  // ==========================================================================
  // requests - Medication demand requests (matches entity/request.rs)
  // ==========================================================================
  requests: defineTable({
    rawMessageId: v.string(),
    sourcePhone: v.string(),
    sourceName: v.optional(v.string()),
    sourceGroup: v.string(),
    medication: v.string(),
    medicationRaw: v.string(),
    quantity: v.optional(v.number()),
    unit: v.optional(v.string()),
    maxPrice: v.optional(v.number()), // Decimal
    currency: v.optional(v.string()),
    urgencyLevel: v.string(),
    expiryRequirement: v.optional(v.string()),
    aiConfidence: v.number(),
    notes: v.optional(v.string()),
    status: v.string(),
    contentEmbedding: v.optional(v.array(v.number())),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_medication", ["medication"])
    .index("by_source", ["sourcePhone"])
    .index("by_raw_message", ["rawMessageId"])
    .index("by_created", ["createdAt"])
    .vectorIndex("by_embedding", {
      vectorField: "contentEmbedding",
      dimensions: 768,
      filterFields: ["status"],
    })
    .searchIndex("search_medication", {
      searchField: "medication",
      filterFields: ["status"],
    }),

  // ==========================================================================
  // matches - Offer-Request matches (matches entity/match_.rs)
  // ==========================================================================
  matches: defineTable({
    // id is auto-generated, SeaORM uses String UUID
    offerId: v.string(), // String FK, NOT v.id
    requestId: v.string(), // String FK, NOT v.id
    score: v.number(), // f64 - NOT "confidence"
    reasoning: v.optional(v.string()),
    matchedBy: v.optional(v.string()), // NOT "confirmedBy"
    status: v.string(), // MatchStatus: "PENDING" | "CONFIRMED" | "REJECTED" | "EXPIRED"
    createdAt: v.number(),
    confirmedAt: v.optional(v.number()),
    notes: v.optional(v.string()),
  })
    .index("by_offer", ["offerId"])
    .index("by_request", ["requestId"])
    .index("by_status", ["status"])
    .index("by_created", ["createdAt"]),

  // ==========================================================================
  // matchQueueItems - Async matching queue (matches entity/match_queue.rs)
  // ==========================================================================
  matchQueueItems: defineTable({
    // id is Uuid in SeaORM, auto-generated in Convex
    requestId: v.string(), // String FK
    status: v.string(), // QueueStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED"
    priority: v.number(), // i32
    attempts: v.number(), // i32
    lastError: v.optional(v.string()),
    nextAttemptAt: v.number(), // DateTimeUtc
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_request", ["requestId"])
    .index("by_created", ["createdAt"]),

  // ==========================================================================
  // reviewQueue - AI parse results for review (matches entity/review_queue.rs)
  // ==========================================================================
  reviewQueue: defineTable({
    // id is Uuid in SeaORM
    rawMessageId: v.string(),
    aiResult: v.any(), // JsonBinary - serde_json::Value
    confidence: v.number(), // f64
    reason: v.string(),
    status: v.string(), // ReviewStatus: "pending" | "approved" | "rejected" | "skipped"
    reviewedBy: v.optional(v.string()),
    reviewNotes: v.optional(v.string()),
    createdAt: v.number(),
    reviewedAt: v.optional(v.number()),
  })
    .index("by_status", ["status"])
    .index("by_raw_message", ["rawMessageId"]),

  // ==========================================================================
  // medicationMappings - Arabic to English mappings (matches entity/medication_mapping.rs)
  // ==========================================================================
  medicationMappings: defineTable({
    // id is String UUID in SeaORM
    arabicName: v.string(),
    englishName: v.string(),
    synonyms: v.optional(v.array(v.string())), // Option<Vec<String>>
    embedding: v.optional(v.array(v.number())), // PgVector(768)
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_arabic", ["arabicName"])
    .index("by_english", ["englishName"]),

  // ==========================================================================
  // auditLogs - Audit trail (matches entity/audit_log.rs)
  // ==========================================================================
  auditLogs: defineTable({
    // id is Uuid in SeaORM
    action: v.string(),
    entityType: v.string(),
    entityId: v.string(),
    actor: v.string(),
    details: v.optional(v.any()), // JsonBinary
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    createdAt: v.number(), // Also part of primary key in SeaORM
  })
    .index("by_entity", ["entityType", "entityId"])
    .index("by_actor", ["actor"])
    .index("by_action", ["action"])
    .index("by_created", ["createdAt"]),

  // ==========================================================================
  // feedbackRecords - User feedback on matches (matches entity/feedback_record.rs)
  // ==========================================================================
  feedbackRecords: defineTable({
    // id is Uuid in SeaORM
    matchId: v.string(), // String FK
    userId: v.string(), // NOT "submittedBy"
    confirmed: v.boolean(), // NOT feedbackType
    // Individual component scores
    medicationScore: v.number(),
    dosageScore: v.number(),
    quantityScore: v.number(),
    priceScore: v.number(),
    recencyScore: v.number(),
    totalScore: v.number(),
    createdAt: v.number(),
  }).index("by_match", ["matchId"]),

  // ==========================================================================
  // weightHistory - Historical weight configurations (matches entity/weight_history.rs)
  // ==========================================================================
  weightHistory: defineTable({
    // id is Uuid in SeaORM
    medicationWeight: v.number(),
    dosageWeight: v.number(),
    quantityWeight: v.number(),
    priceWeight: v.number(),
    recencyWeight: v.number(),
    source: v.string(), // NOT "changedBy"
    sampleCount: v.number(), // NOT "feedbackCount"
    createdAt: v.number(),
  }).index("by_created", ["createdAt"]),
});
