package storage

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"pharmabroker/internal/domain"

	_ "modernc.org/sqlite" // Ensure driver is available
)

func setupTestDB(t *testing.T) *DB {
	// Use in-memory DB
	conn, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatalf("Failed to open DB: %v", err)
	}

	db := &DB{writer: conn, reader: conn}

	// Run migration manually (simplified for test)
	_, err = conn.Exec(`
		CREATE TABLE raw_messages (
			id TEXT PRIMARY KEY,
			group_jid TEXT,
			group_name TEXT,
			sender_jid TEXT,
			sender_phone TEXT,
			sender_name TEXT,
			content TEXT,
			timestamp DATETIME,
			processed_at DATETIME,
			error TEXT,
			external_id TEXT
		);
		CREATE UNIQUE INDEX idx_raw_messages_external_id ON raw_messages(external_id);
	`)
	if err != nil {
		t.Fatalf("Failed to migrate DB: %v", err)
	}

	return db
}

func TestRawMessageRepo_Save_Deduplication(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRawMessageRepo(db)
	ctx := context.Background()

	// 1. Insert first message
	msg1 := &domain.RawMessage{
		ID:         "internal-id-1",
		ExternalID: "whatsapp-id-123",
		GroupJID:   "group-1",
		Content:    "Hello",
		Timestamp:  time.Now(),
	}

	err := repo.Save(ctx, msg1)
	if err != nil {
		t.Fatalf("First Save failed: %v", err)
	}

	// 2. Insert duplicate (history sync) with same ExternalID but new Internal ID
	msg2 := &domain.RawMessage{
		ID:         "internal-id-2",   // Different internal ID (generated by listener)
		ExternalID: "whatsapp-id-123", // Same External ID
		GroupJID:   "group-1",
		Content:    "Hello Updated", // Content might match or not
		Timestamp:  msg1.Timestamp,
	}

	err = repo.Save(ctx, msg2)
	if err != nil {
		t.Fatalf("Second Save (Duplicate) failed: %v", err)
	}

	// 3. Verify count is 1
	var count int
	err = db.Conn().QueryRow("SELECT COUNT(*) FROM raw_messages").Scan(&count)
	if err != nil {
		t.Fatalf("Count failed: %v", err)
	}

	if count != 1 {
		t.Errorf("Expected 1 message, got %d", count)
	}

	// 4. Verify content was updated (UPSERT logic)
	// Query by the original ID because UPSERT kept the original row (and thus the original ID)
	savedMsg, err := repo.GetByID(ctx, "internal-id-1")
	if err != nil {
		t.Fatalf("GetByID failed: %v", err)
	}

	if savedMsg.Content != "Hello Updated" {
		t.Errorf("Expected content 'Hello Updated', got '%s'", savedMsg.Content)
	}
}
