//! gRPC Server Implementation
//!
//! Handles messages from the Go WhatsApp bridge

use std::net::SocketAddr;
use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::repository::{OfferRepository, RawMessageRepository, RequestRepository};

/// Generated proto types - will be generated by build.rs
/// For now, we define them manually to avoid build-time proto compilation
pub mod proto {
    /// Raw message from WhatsApp
    #[derive(Debug, Clone)]
    pub struct RawMessage {
        pub id: String,
        pub external_id: String,
        pub group_jid: String,
        pub group_name: String,
        pub sender_jid: String,
        pub sender_phone: String,
        pub sender_name: String,
        pub content: String,
        pub timestamp: i64,
        pub reply_to_id: Option<String>,
        pub reply_to_content: Option<String>,
        pub reply_to_sender: Option<String>,
    }

    /// Response after processing a message
    #[derive(Debug)]
    pub struct ProcessResponse {
        pub success: bool,
        pub message_id: String,
        pub error: Option<String>,
    }

    /// Stats response
    #[derive(Debug)]
    pub struct StatsResponse {
        pub active_offers: i64,
        pub active_requests: i64,
        pub pending_matches: i64,
        pub confirmed_today: i64,
        pub processed_today: i64,
        pub avg_match_score: f64,
    }

    /// Health response
    #[derive(Debug)]
    pub struct HealthResponse {
        pub healthy: bool,
        pub version: String,
        pub uptime_seconds: i64,
    }
}

/// The gRPC service implementation
pub struct PharmaCoreService<O, R>
where
    O: OfferRepository + 'static,
    R: RequestRepository + 'static,
{
    offer_repo: Arc<O>,
    request_repo: Arc<R>,
    start_time: std::time::Instant,
}

impl<O, R> PharmaCoreService<O, R>
where
    O: OfferRepository + 'static,
    R: RequestRepository + 'static,
{
    pub fn new(offer_repo: Arc<O>, request_repo: Arc<R>) -> Self {
        Self {
            offer_repo,
            request_repo,
            start_time: std::time::Instant::now(),
        }
    }

    /// Process an incoming WhatsApp message
    pub async fn process_message(
        &self,
        msg: proto::RawMessage,
    ) -> Result<proto::ProcessResponse, Status> {
        tracing::info!(
            group = %msg.group_jid,
            sender = %msg.sender_phone,
            content_len = msg.content.len(),
            "Processing message from Go bridge"
        );

        // TODO: Integrate with AI parsing pipeline
        // TODO: Create offers/requests based on parsed content
        // TODO: Trigger matching engine

        Ok(proto::ProcessResponse {
            success: true,
            message_id: msg.id,
            error: None,
        })
    }

    /// Get current statistics
    pub async fn get_stats(&self) -> Result<proto::StatsResponse, Status> {
        let active_offers = self.offer_repo.count_active().await.unwrap_or(0);
        let active_requests = self.request_repo.count_active().await.unwrap_or(0);

        Ok(proto::StatsResponse {
            active_offers,
            active_requests,
            pending_matches: 0,
            confirmed_today: 0,
            processed_today: 0,
            avg_match_score: 0.0,
        })
    }

    /// Health check
    pub fn health_check(&self) -> proto::HealthResponse {
        proto::HealthResponse {
            healthy: true,
            version: "0.1.0".to_string(),
            uptime_seconds: self.start_time.elapsed().as_secs() as i64,
        }
    }
}

/// Start the gRPC server on the specified port
///
/// Note: This is a simplified implementation without full tonic codegen.
/// In production, you would use tonic-build to generate the service trait.
pub async fn start_grpc_server(addr: SocketAddr) -> anyhow::Result<()> {
    tracing::info!("gRPC server would start on {}", addr);
    tracing::info!("Note: Full tonic implementation requires proto compilation");

    // In a full implementation:
    // let service = PharmaCoreServer::new(pharma_service);
    // Server::builder()
    //     .add_service(service)
    //     .serve(addr)
    //     .await?;

    Ok(())
}
