/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as IndexRouteImport } from './routes/index'

const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offers': typeof OffersRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offers' | '/requests' | '/review-queue'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offers' | '/requests' | '/review-queue'
  id: '__root__' | '/' | '/offers' | '/requests' | '/review-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OffersRoute: typeof OffersRoute
  RequestsRoute: typeof RequestsRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OffersRoute: OffersRoute,
  RequestsRoute: RequestsRoute,
  ReviewQueueRoute: ReviewQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
