/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ParsingReviewRouteImport } from './routes/parsing-review'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DebugRecordingsRouteImport } from './routes/debug-recordings'
import { Route as IndexRouteImport } from './routes/index'

const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ParsingReviewRoute = ParsingReviewRouteImport.update({
  id: '/parsing-review',
  path: '/parsing-review',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRecordingsRoute = DebugRecordingsRouteImport.update({
  id: '/debug-recordings',
  path: '/debug-recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug-recordings': typeof DebugRecordingsRoute
  '/groups': typeof GroupsRoute
  '/matches': typeof MatchesRoute
  '/offers': typeof OffersRoute
  '/parsing-review': typeof ParsingReviewRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/supervision': typeof SupervisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-recordings': typeof DebugRecordingsRoute
  '/groups': typeof GroupsRoute
  '/matches': typeof MatchesRoute
  '/offers': typeof OffersRoute
  '/parsing-review': typeof ParsingReviewRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/supervision': typeof SupervisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug-recordings': typeof DebugRecordingsRoute
  '/groups': typeof GroupsRoute
  '/matches': typeof MatchesRoute
  '/offers': typeof OffersRoute
  '/parsing-review': typeof ParsingReviewRoute
  '/requests': typeof RequestsRoute
  '/review-queue': typeof ReviewQueueRoute
  '/supervision': typeof SupervisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug-recordings'
    | '/groups'
    | '/matches'
    | '/offers'
    | '/parsing-review'
    | '/requests'
    | '/review-queue'
    | '/supervision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-recordings'
    | '/groups'
    | '/matches'
    | '/offers'
    | '/parsing-review'
    | '/requests'
    | '/review-queue'
    | '/supervision'
  id:
    | '__root__'
    | '/'
    | '/debug-recordings'
    | '/groups'
    | '/matches'
    | '/offers'
    | '/parsing-review'
    | '/requests'
    | '/review-queue'
    | '/supervision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRecordingsRoute: typeof DebugRecordingsRoute
  GroupsRoute: typeof GroupsRoute
  MatchesRoute: typeof MatchesRoute
  OffersRoute: typeof OffersRoute
  ParsingReviewRoute: typeof ParsingReviewRoute
  RequestsRoute: typeof RequestsRoute
  ReviewQueueRoute: typeof ReviewQueueRoute
  SupervisionRoute: typeof SupervisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parsing-review': {
      id: '/parsing-review'
      path: '/parsing-review'
      fullPath: '/parsing-review'
      preLoaderRoute: typeof ParsingReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-recordings': {
      id: '/debug-recordings'
      path: '/debug-recordings'
      fullPath: '/debug-recordings'
      preLoaderRoute: typeof DebugRecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRecordingsRoute: DebugRecordingsRoute,
  GroupsRoute: GroupsRoute,
  MatchesRoute: MatchesRoute,
  OffersRoute: OffersRoute,
  ParsingReviewRoute: ParsingReviewRoute,
  RequestsRoute: RequestsRoute,
  ReviewQueueRoute: ReviewQueueRoute,
  SupervisionRoute: SupervisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
