// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/pharma.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawMessage represents an incoming WhatsApp message
type RawMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId  string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	GroupJid    string                 `protobuf:"bytes,3,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	GroupName   string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SenderJid   string                 `protobuf:"bytes,5,opt,name=sender_jid,json=senderJid,proto3" json:"sender_jid,omitempty"`
	SenderPhone string                 `protobuf:"bytes,6,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	SenderName  string                 `protobuf:"bytes,7,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content     string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp   int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Reply context
	ReplyToId      *string `protobuf:"bytes,10,opt,name=reply_to_id,json=replyToId,proto3,oneof" json:"reply_to_id,omitempty"`
	ReplyToContent *string `protobuf:"bytes,11,opt,name=reply_to_content,json=replyToContent,proto3,oneof" json:"reply_to_content,omitempty"`
	ReplyToSender  *string `protobuf:"bytes,12,opt,name=reply_to_sender,json=replyToSender,proto3,oneof" json:"reply_to_sender,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_proto_pharma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{0}
}

func (x *RawMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RawMessage) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *RawMessage) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

func (x *RawMessage) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *RawMessage) GetSenderJid() string {
	if x != nil {
		return x.SenderJid
	}
	return ""
}

func (x *RawMessage) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *RawMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *RawMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RawMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RawMessage) GetReplyToId() string {
	if x != nil && x.ReplyToId != nil {
		return *x.ReplyToId
	}
	return ""
}

func (x *RawMessage) GetReplyToContent() string {
	if x != nil && x.ReplyToContent != nil {
		return *x.ReplyToContent
	}
	return ""
}

func (x *RawMessage) GetReplyToSender() string {
	if x != nil && x.ReplyToSender != nil {
		return *x.ReplyToSender
	}
	return ""
}

// ProcessResponse indicates the result of message processing
type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_pharma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProcessResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// StatsRequest for getting system statistics
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_pharma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{2}
}

// StatsResponse with current system statistics
type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveOffers   int64                  `protobuf:"varint,1,opt,name=active_offers,json=activeOffers,proto3" json:"active_offers,omitempty"`
	ActiveRequests int64                  `protobuf:"varint,2,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	PendingMatches int64                  `protobuf:"varint,3,opt,name=pending_matches,json=pendingMatches,proto3" json:"pending_matches,omitempty"`
	ConfirmedToday int64                  `protobuf:"varint,4,opt,name=confirmed_today,json=confirmedToday,proto3" json:"confirmed_today,omitempty"`
	ProcessedToday int64                  `protobuf:"varint,5,opt,name=processed_today,json=processedToday,proto3" json:"processed_today,omitempty"`
	AvgMatchScore  float64                `protobuf:"fixed64,6,opt,name=avg_match_score,json=avgMatchScore,proto3" json:"avg_match_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_pharma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetActiveOffers() int64 {
	if x != nil {
		return x.ActiveOffers
	}
	return 0
}

func (x *StatsResponse) GetActiveRequests() int64 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *StatsResponse) GetPendingMatches() int64 {
	if x != nil {
		return x.PendingMatches
	}
	return 0
}

func (x *StatsResponse) GetConfirmedToday() int64 {
	if x != nil {
		return x.ConfirmedToday
	}
	return 0
}

func (x *StatsResponse) GetProcessedToday() int64 {
	if x != nil {
		return x.ProcessedToday
	}
	return 0
}

func (x *StatsResponse) GetAvgMatchScore() float64 {
	if x != nil {
		return x.AvgMatchScore
	}
	return 0
}

// HealthRequest for health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_pharma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{4}
}

// HealthResponse indicating service health
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_pharma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// MonitoredGroupsRequest for getting monitored group JIDs
type MonitoredGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoredGroupsRequest) Reset() {
	*x = MonitoredGroupsRequest{}
	mi := &file_proto_pharma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoredGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoredGroupsRequest) ProtoMessage() {}

func (x *MonitoredGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoredGroupsRequest.ProtoReflect.Descriptor instead.
func (*MonitoredGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{6}
}

// MonitoredGroupsResponse with list of JIDs
type MonitoredGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jids          []string               `protobuf:"bytes,1,rep,name=jids,proto3" json:"jids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoredGroupsResponse) Reset() {
	*x = MonitoredGroupsResponse{}
	mi := &file_proto_pharma_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoredGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoredGroupsResponse) ProtoMessage() {}

func (x *MonitoredGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoredGroupsResponse.ProtoReflect.Descriptor instead.
func (*MonitoredGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{7}
}

func (x *MonitoredGroupsResponse) GetJids() []string {
	if x != nil {
		return x.Jids
	}
	return nil
}

// GroupInfo represents a WhatsApp group
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_pharma_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{8}
}

func (x *GroupInfo) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SyncGroupsRequest for syncing groups from Bridge to Core
type SyncGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupInfo           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGroupsRequest) Reset() {
	*x = SyncGroupsRequest{}
	mi := &file_proto_pharma_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupsRequest) ProtoMessage() {}

func (x *SyncGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupsRequest.ProtoReflect.Descriptor instead.
func (*SyncGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{9}
}

func (x *SyncGroupsRequest) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

// SyncGroupsResponse with sync results
type SyncGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Added         int32                  `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"`
	Updated       int32                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGroupsResponse) Reset() {
	*x = SyncGroupsResponse{}
	mi := &file_proto_pharma_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupsResponse) ProtoMessage() {}

func (x *SyncGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pharma_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupsResponse.ProtoReflect.Descriptor instead.
func (*SyncGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pharma_proto_rawDescGZIP(), []int{10}
}

func (x *SyncGroupsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncGroupsResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *SyncGroupsResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *SyncGroupsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_pharma_proto protoreflect.FileDescriptor

const file_proto_pharma_proto_rawDesc = "" +
	"\n" +
	"\x12proto/pharma.proto\x12\x06pharma\"\xce\x03\n" +
	"\n" +
	"RawMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1b\n" +
	"\tgroup_jid\x18\x03 \x01(\tR\bgroupJid\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"sender_jid\x18\x05 \x01(\tR\tsenderJid\x12!\n" +
	"\fsender_phone\x18\x06 \x01(\tR\vsenderPhone\x12\x1f\n" +
	"\vsender_name\x18\a \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12#\n" +
	"\vreply_to_id\x18\n" +
	" \x01(\tH\x00R\treplyToId\x88\x01\x01\x12-\n" +
	"\x10reply_to_content\x18\v \x01(\tH\x01R\x0ereplyToContent\x88\x01\x01\x12+\n" +
	"\x0freply_to_sender\x18\f \x01(\tH\x02R\rreplyToSender\x88\x01\x01B\x0e\n" +
	"\f_reply_to_idB\x13\n" +
	"\x11_reply_to_contentB\x12\n" +
	"\x10_reply_to_sender\"o\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x0e\n" +
	"\fStatsRequest\"\x80\x02\n" +
	"\rStatsResponse\x12#\n" +
	"\ractive_offers\x18\x01 \x01(\x03R\factiveOffers\x12'\n" +
	"\x0factive_requests\x18\x02 \x01(\x03R\x0eactiveRequests\x12'\n" +
	"\x0fpending_matches\x18\x03 \x01(\x03R\x0ependingMatches\x12'\n" +
	"\x0fconfirmed_today\x18\x04 \x01(\x03R\x0econfirmedToday\x12'\n" +
	"\x0fprocessed_today\x18\x05 \x01(\x03R\x0eprocessedToday\x12&\n" +
	"\x0favg_match_score\x18\x06 \x01(\x01R\ravgMatchScore\"\x0f\n" +
	"\rHealthRequest\"k\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x18\n" +
	"\x16MonitoredGroupsRequest\"-\n" +
	"\x17MonitoredGroupsResponse\x12\x12\n" +
	"\x04jids\x18\x01 \x03(\tR\x04jids\"S\n" +
	"\tGroupInfo\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\">\n" +
	"\x11SyncGroupsRequest\x12)\n" +
	"\x06groups\x18\x01 \x03(\v2\x11.pharma.GroupInfoR\x06groups\"t\n" +
	"\x12SyncGroupsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05added\x18\x02 \x01(\x05R\x05added\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x05R\aupdated\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xde\x02\n" +
	"\n" +
	"PharmaCore\x12=\n" +
	"\x0eProcessMessage\x12\x12.pharma.RawMessage\x1a\x17.pharma.ProcessResponse\x127\n" +
	"\bGetStats\x12\x14.pharma.StatsRequest\x1a\x15.pharma.StatsResponse\x12<\n" +
	"\vHealthCheck\x12\x15.pharma.HealthRequest\x1a\x16.pharma.HealthResponse\x12U\n" +
	"\x12GetMonitoredGroups\x12\x1e.pharma.MonitoredGroupsRequest\x1a\x1f.pharma.MonitoredGroupsResponse\x12C\n" +
	"\n" +
	"SyncGroups\x12\x19.pharma.SyncGroupsRequest\x1a\x1a.pharma.SyncGroupsResponseB\x15Z\x13pharma-bridge/protob\x06proto3"

var (
	file_proto_pharma_proto_rawDescOnce sync.Once
	file_proto_pharma_proto_rawDescData []byte
)

func file_proto_pharma_proto_rawDescGZIP() []byte {
	file_proto_pharma_proto_rawDescOnce.Do(func() {
		file_proto_pharma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pharma_proto_rawDesc), len(file_proto_pharma_proto_rawDesc)))
	})
	return file_proto_pharma_proto_rawDescData
}

var file_proto_pharma_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_pharma_proto_goTypes = []any{
	(*RawMessage)(nil),              // 0: pharma.RawMessage
	(*ProcessResponse)(nil),         // 1: pharma.ProcessResponse
	(*StatsRequest)(nil),            // 2: pharma.StatsRequest
	(*StatsResponse)(nil),           // 3: pharma.StatsResponse
	(*HealthRequest)(nil),           // 4: pharma.HealthRequest
	(*HealthResponse)(nil),          // 5: pharma.HealthResponse
	(*MonitoredGroupsRequest)(nil),  // 6: pharma.MonitoredGroupsRequest
	(*MonitoredGroupsResponse)(nil), // 7: pharma.MonitoredGroupsResponse
	(*GroupInfo)(nil),               // 8: pharma.GroupInfo
	(*SyncGroupsRequest)(nil),       // 9: pharma.SyncGroupsRequest
	(*SyncGroupsResponse)(nil),      // 10: pharma.SyncGroupsResponse
}
var file_proto_pharma_proto_depIdxs = []int32{
	8,  // 0: pharma.SyncGroupsRequest.groups:type_name -> pharma.GroupInfo
	0,  // 1: pharma.PharmaCore.ProcessMessage:input_type -> pharma.RawMessage
	2,  // 2: pharma.PharmaCore.GetStats:input_type -> pharma.StatsRequest
	4,  // 3: pharma.PharmaCore.HealthCheck:input_type -> pharma.HealthRequest
	6,  // 4: pharma.PharmaCore.GetMonitoredGroups:input_type -> pharma.MonitoredGroupsRequest
	9,  // 5: pharma.PharmaCore.SyncGroups:input_type -> pharma.SyncGroupsRequest
	1,  // 6: pharma.PharmaCore.ProcessMessage:output_type -> pharma.ProcessResponse
	3,  // 7: pharma.PharmaCore.GetStats:output_type -> pharma.StatsResponse
	5,  // 8: pharma.PharmaCore.HealthCheck:output_type -> pharma.HealthResponse
	7,  // 9: pharma.PharmaCore.GetMonitoredGroups:output_type -> pharma.MonitoredGroupsResponse
	10, // 10: pharma.PharmaCore.SyncGroups:output_type -> pharma.SyncGroupsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pharma_proto_init() }
func file_proto_pharma_proto_init() {
	if File_proto_pharma_proto != nil {
		return
	}
	file_proto_pharma_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_pharma_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pharma_proto_rawDesc), len(file_proto_pharma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pharma_proto_goTypes,
		DependencyIndexes: file_proto_pharma_proto_depIdxs,
		MessageInfos:      file_proto_pharma_proto_msgTypes,
	}.Build()
	File_proto_pharma_proto = out.File
	file_proto_pharma_proto_goTypes = nil
	file_proto_pharma_proto_depIdxs = nil
}
