// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/pharma.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PharmaCore_ProcessMessage_FullMethodName     = "/pharma.PharmaCore/ProcessMessage"
	PharmaCore_GetStats_FullMethodName           = "/pharma.PharmaCore/GetStats"
	PharmaCore_HealthCheck_FullMethodName        = "/pharma.PharmaCore/HealthCheck"
	PharmaCore_GetMonitoredGroups_FullMethodName = "/pharma.PharmaCore/GetMonitoredGroups"
	PharmaCore_SyncGroups_FullMethodName         = "/pharma.PharmaCore/SyncGroups"
)

// PharmaCoreClient is the client API for PharmaCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PharmaCoreService is the main service interface for the Rust core engine
type PharmaCoreClient interface {
	// ProcessMessage handles incoming WhatsApp messages
	ProcessMessage(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*ProcessResponse, error)
	// GetStats returns current system statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// HealthCheck verifies the service is running
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetMonitoredGroups returns a list of JIDs that should be monitored
	GetMonitoredGroups(ctx context.Context, in *MonitoredGroupsRequest, opts ...grpc.CallOption) (*MonitoredGroupsResponse, error)
	// SyncGroups syncs WhatsApp groups from Bridge to Core
	SyncGroups(ctx context.Context, in *SyncGroupsRequest, opts ...grpc.CallOption) (*SyncGroupsResponse, error)
}

type pharmaCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmaCoreClient(cc grpc.ClientConnInterface) PharmaCoreClient {
	return &pharmaCoreClient{cc}
}

func (c *pharmaCoreClient) ProcessMessage(ctx context.Context, in *RawMessage, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, PharmaCore_ProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmaCoreClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, PharmaCore_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmaCoreClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PharmaCore_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmaCoreClient) GetMonitoredGroups(ctx context.Context, in *MonitoredGroupsRequest, opts ...grpc.CallOption) (*MonitoredGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoredGroupsResponse)
	err := c.cc.Invoke(ctx, PharmaCore_GetMonitoredGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmaCoreClient) SyncGroups(ctx context.Context, in *SyncGroupsRequest, opts ...grpc.CallOption) (*SyncGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncGroupsResponse)
	err := c.cc.Invoke(ctx, PharmaCore_SyncGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmaCoreServer is the server API for PharmaCore service.
// All implementations must embed UnimplementedPharmaCoreServer
// for forward compatibility.
//
// PharmaCoreService is the main service interface for the Rust core engine
type PharmaCoreServer interface {
	// ProcessMessage handles incoming WhatsApp messages
	ProcessMessage(context.Context, *RawMessage) (*ProcessResponse, error)
	// GetStats returns current system statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// HealthCheck verifies the service is running
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetMonitoredGroups returns a list of JIDs that should be monitored
	GetMonitoredGroups(context.Context, *MonitoredGroupsRequest) (*MonitoredGroupsResponse, error)
	// SyncGroups syncs WhatsApp groups from Bridge to Core
	SyncGroups(context.Context, *SyncGroupsRequest) (*SyncGroupsResponse, error)
	mustEmbedUnimplementedPharmaCoreServer()
}

// UnimplementedPharmaCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmaCoreServer struct{}

func (UnimplementedPharmaCoreServer) ProcessMessage(context.Context, *RawMessage) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedPharmaCoreServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedPharmaCoreServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPharmaCoreServer) GetMonitoredGroups(context.Context, *MonitoredGroupsRequest) (*MonitoredGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonitoredGroups not implemented")
}
func (UnimplementedPharmaCoreServer) SyncGroups(context.Context, *SyncGroupsRequest) (*SyncGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGroups not implemented")
}
func (UnimplementedPharmaCoreServer) mustEmbedUnimplementedPharmaCoreServer() {}
func (UnimplementedPharmaCoreServer) testEmbeddedByValue()                    {}

// UnsafePharmaCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmaCoreServer will
// result in compilation errors.
type UnsafePharmaCoreServer interface {
	mustEmbedUnimplementedPharmaCoreServer()
}

func RegisterPharmaCoreServer(s grpc.ServiceRegistrar, srv PharmaCoreServer) {
	// If the following call panics, it indicates UnimplementedPharmaCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmaCore_ServiceDesc, srv)
}

func _PharmaCore_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaCoreServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaCore_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaCoreServer).ProcessMessage(ctx, req.(*RawMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmaCore_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaCoreServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaCore_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaCoreServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmaCore_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaCoreServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaCore_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaCoreServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmaCore_GetMonitoredGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoredGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaCoreServer).GetMonitoredGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaCore_GetMonitoredGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaCoreServer).GetMonitoredGroups(ctx, req.(*MonitoredGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmaCore_SyncGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaCoreServer).SyncGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaCore_SyncGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaCoreServer).SyncGroups(ctx, req.(*SyncGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmaCore_ServiceDesc is the grpc.ServiceDesc for PharmaCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmaCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharma.PharmaCore",
	HandlerType: (*PharmaCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _PharmaCore_ProcessMessage_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _PharmaCore_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PharmaCore_HealthCheck_Handler,
		},
		{
			MethodName: "GetMonitoredGroups",
			Handler:    _PharmaCore_GetMonitoredGroups_Handler,
		},
		{
			MethodName: "SyncGroups",
			Handler:    _PharmaCore_SyncGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pharma.proto",
}

const (
	PharmaBridge_ConnectMatch_FullMethodName = "/pharma.PharmaBridge/ConnectMatch"
)

// PharmaBridgeClient is the client API for PharmaBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PharmaBridgeService is the interface for Core to call Bridge
type PharmaBridgeClient interface {
	// ConnectMatch tells the bridge to notify parties (and operator) about a match
	ConnectMatch(ctx context.Context, in *ConnectMatchRequest, opts ...grpc.CallOption) (*ConnectMatchResponse, error)
}

type pharmaBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmaBridgeClient(cc grpc.ClientConnInterface) PharmaBridgeClient {
	return &pharmaBridgeClient{cc}
}

func (c *pharmaBridgeClient) ConnectMatch(ctx context.Context, in *ConnectMatchRequest, opts ...grpc.CallOption) (*ConnectMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectMatchResponse)
	err := c.cc.Invoke(ctx, PharmaBridge_ConnectMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmaBridgeServer is the server API for PharmaBridge service.
// All implementations must embed UnimplementedPharmaBridgeServer
// for forward compatibility.
//
// PharmaBridgeService is the interface for Core to call Bridge
type PharmaBridgeServer interface {
	// ConnectMatch tells the bridge to notify parties (and operator) about a match
	ConnectMatch(context.Context, *ConnectMatchRequest) (*ConnectMatchResponse, error)
	mustEmbedUnimplementedPharmaBridgeServer()
}

// UnimplementedPharmaBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmaBridgeServer struct{}

func (UnimplementedPharmaBridgeServer) ConnectMatch(context.Context, *ConnectMatchRequest) (*ConnectMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectMatch not implemented")
}
func (UnimplementedPharmaBridgeServer) mustEmbedUnimplementedPharmaBridgeServer() {}
func (UnimplementedPharmaBridgeServer) testEmbeddedByValue()                      {}

// UnsafePharmaBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmaBridgeServer will
// result in compilation errors.
type UnsafePharmaBridgeServer interface {
	mustEmbedUnimplementedPharmaBridgeServer()
}

func RegisterPharmaBridgeServer(s grpc.ServiceRegistrar, srv PharmaBridgeServer) {
	// If the following call panics, it indicates UnimplementedPharmaBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmaBridge_ServiceDesc, srv)
}

func _PharmaBridge_ConnectMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmaBridgeServer).ConnectMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmaBridge_ConnectMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmaBridgeServer).ConnectMatch(ctx, req.(*ConnectMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmaBridge_ServiceDesc is the grpc.ServiceDesc for PharmaBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmaBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharma.PharmaBridge",
	HandlerType: (*PharmaBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectMatch",
			Handler:    _PharmaBridge_ConnectMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pharma.proto",
}
